name: Add New Activity
description: Request to add a new extracurricular activity to the system
title: "[New Activity]: "
labels: ["enhancement", "activity"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our activities system! Please fill out the information below to add a new extracurricular activity.
        
  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: What is the name of the new activity?
      placeholder: "e.g., Chess Club, Drama Club, Science Olympiad"
    validations:
      required: true
      
  - type: textarea
    id: activity-description
    attributes:
      label: Activity Description
      description: Provide a brief description of what this activity is about
      placeholder: "Describe the activity, what students will do, and what they'll learn"
    validations:
      required: true
      
  - type: input
    id: meeting-schedule
    attributes:
      label: Meeting Schedule
      description: When will this activity meet? (days and times)
      placeholder: "e.g., Tuesdays and Thursdays, 3:30 PM - 5:00 PM"
    validations:
      required: true
      
  - type: input
    id: max-participants
    attributes:
      label: Maximum Participants
      description: What is the maximum number of students that can participate?
      placeholder: "e.g., 20"
    validations:
      required: true
      
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that should be included (prerequisites, materials needed, etc.)
      placeholder: "Any special requirements or information?"
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        - [ ] New activity is added to the activities list
        - [ ] Activity includes all required information (name, description, schedule, max participants)
        - [ ] Students can view the new activity on the website
        - [ ] Students can sign up for the activity
        
        ## Implementation Hints
        - The activity data is stored in `src/backend/database.py`
        - New activities should be added to the `initial_activities` dictionary
        - Each activity should have: description, schedule, schedule_details (with days, start_time, end_time), max_participants, and participants (initially an empty list)
        - The activity name is used as the key in the dictionary
