blank_issues_enabled: false
contact_links:
  - name: General Question or Discussion
    url: https://github.com/Edso-as/skills-expand-your-team-with-copilot/discussions
    about: For questions or discussions that don't fit the templates above, please use GitHub Discussions
